#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

$app = new \Core\Application(realpath(__DIR__));

$kernel = new App\Console\Kernel($app);

$status = $kernel->handle(
    $input = new Symfony\Component\Console\Input\ArgvInput,
    new Symfony\Component\Console\Output\ConsoleOutput
);

exit($status);
